/*
 * generated by Xtext 2.10.0
 */
package skysail.product.prototypr.dsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ApplicationStandaloneSetup extends ApplicationStandaloneSetupGenerated {

	def static void doSetup() {
		new ApplicationStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
