/*
 * generated by Xtext 2.10.0
 */
package skysail.product.prototypr.dsl.idea.highlighting;

import com.intellij.openapi.fileTypes.SingleLazyInstanceSyntaxHighlighterFactory;
import com.intellij.openapi.fileTypes.SyntaxHighlighter;
import org.jetbrains.annotations.NotNull;
import skysail.product.prototypr.dsl.idea.lang.ApplicationLanguage;

public class ApplicationSyntaxHighlighterFactory extends SingleLazyInstanceSyntaxHighlighterFactory {
	
	@Override
	@NotNull
	protected SyntaxHighlighter createHighlighter() {
		return ApplicationLanguage.INSTANCE.getInstance(SyntaxHighlighter.class);
	}
}
