/*
 * generated by Xtext 2.10.0
 */
package skysail.product.prototypr.dsl.idea.highlighting;

import org.eclipse.xtext.idea.highlighting.AbstractColorSettingsPage;
import skysail.product.prototypr.dsl.idea.lang.ApplicationLanguage;

public class ApplicationBaseColorSettingsPage extends AbstractColorSettingsPage {
	
	public ApplicationBaseColorSettingsPage() {
		ApplicationLanguage.INSTANCE.injectMembers(this);
	}

	@Override
	public String getDisplayName() {
		return ApplicationLanguage.INSTANCE.getDisplayName();
	}
}
