/**
 * generated by Xtext 2.10.0
 */
package skysail.product.prototypr.dsl.application.impl;

import org.eclipse.emf.ecore.EClass;

import skysail.product.prototypr.dsl.application.ApplicationPackage;
import skysail.product.prototypr.dsl.application.Property;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Property</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class PropertyImpl extends FeatureImpl implements Property
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PropertyImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ApplicationPackage.Literals.PROPERTY;
  }

} //PropertyImpl
