/**
 * generated by Xtext 2.10.0
 */
package skysail.product.prototypr.dsl.ui.contentassist;

import skysail.product.prototypr.dsl.ui.contentassist.AbstractApplicationProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class ApplicationProposalProvider extends AbstractApplicationProposalProvider {
}
