/*
 * generated by Xtext 2.10.0
 */
package skysail.product.prototypr.dsl.idea


/**
 * Use this class to register components to be used within IntelliJ IDEA.
 */
class ApplicationIdeaModule extends AbstractApplicationIdeaModule {
}
