/**
 * generated by Xtext 2.10.0
 */
package skysail.product.prototypr.dsl.application;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Property</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see skysail.product.prototypr.dsl.application.ApplicationPackage#getProperty()
 * @model
 * @generated
 */
public interface Property extends Feature
{
} // Property
