/*
 * generated by Xtext 2.10.0
 */
package skysail.product.prototypr.dsl.idea.lang


class ApplicationFileType extends AbstractApplicationFileType {
	public static final ApplicationFileType INSTANCE = new ApplicationFileType()
	
	new() {
		super(ApplicationLanguage.INSTANCE)
	}
}
