/*
 * generated by Xtext 2.10.0
 */
package skysail.product.prototypr.dsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.junit4.IInjectorProvider;
import skysail.product.prototypr.dsl.ui.internal.DslActivator;

public class ApplicationUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return DslActivator.getInstance().getInjector("skysail.product.prototypr.dsl.Application");
	}

}
