/*
 * generated by Xtext 2.10.0
 */
package skysail.product.prototypr.dsl.idea.lang;

import com.intellij.openapi.fileTypes.FileTypeConsumer;
import com.intellij.openapi.fileTypes.FileTypeFactory;
import org.jetbrains.annotations.NotNull;

public class ApplicationFileTypeFactory extends FileTypeFactory {

	@Override
	public void createFileTypes(@NotNull FileTypeConsumer consumer) {
		consumer.consume(ApplicationFileType.INSTANCE, AbstractApplicationFileType.DEFAULT_EXTENSION);
	}

}
