/*
 * generated by Xtext 2.10.0
 */
package skysail.product.prototypr.dsl.idea.lang;

import org.eclipse.xtext.idea.lang.AbstractXtextLanguage;

public final class ApplicationLanguage extends AbstractXtextLanguage {

	public static final ApplicationLanguage INSTANCE = new ApplicationLanguage();

	private ApplicationLanguage() {
		super("skysail.product.prototypr.dsl.Application");
	}

}
