/*
 * generated by Xtext 2.10.0
 */
package skysail.product.prototypr.dsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractApplicationScopeProvider extends DelegatingScopeProvider {
}
