/*
 * generated by Xtext 2.10.0
 */
package skysail.product.prototypr.dsl.scoping;

import org.eclipse.xtext.xbase.scoping.batch.XbaseBatchScopeProvider;

public abstract class AbstractApplicationScopeProvider extends XbaseBatchScopeProvider {
}
