/*
 * generated by Xtext 2.10.0
 */
package skysail.product.prototypr.dsl.idea.lang.pom;

import org.eclipse.xtext.idea.pom.AbstractXtextPomDeclarationSearcher;
import skysail.product.prototypr.dsl.idea.lang.ApplicationLanguage;

public class ApplicationPomDeclarationSearcher extends AbstractXtextPomDeclarationSearcher {

	public ApplicationPomDeclarationSearcher() {
		super(ApplicationLanguage.INSTANCE);
	}
}
