/*
 * generated by Xtext 2.10.0
 */
package skysail.product.prototypr.dsl.idea.completion;

import org.eclipse.xtext.common.idea.completion.TerminalsCompletionContributor;
import org.eclipse.xtext.idea.lang.AbstractXtextLanguage;

public class AbstractApplicationCompletionContributor extends TerminalsCompletionContributor {
	public AbstractApplicationCompletionContributor(AbstractXtextLanguage lang) {
		super(lang);
	}
}
