/**
 * generated by Xtext 2.10.0
 */
package skysail.product.prototypr.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import skysail.product.prototypr.dsl.ui.AbstractApplicationUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class ApplicationUiModule extends AbstractApplicationUiModule {
  public ApplicationUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
