/*
 * generated by Xtext 2.10.0
 */
package skysail.product.prototypr.dsl.idea;

import com.intellij.openapi.extensions.ExtensionFactory;
import skysail.product.prototypr.dsl.idea.lang.ApplicationLanguage;

public class ApplicationExtensionFactory implements ExtensionFactory {
	@Override
	public Object createInstance(String factoryArgument, String implementationClass) {
		Class<?> clazz;
		try {
			clazz = Class.forName(implementationClass);
		} catch (ClassNotFoundException e) {
			throw new IllegalArgumentException("Couldn't load "+implementationClass, e);
		}
		return ApplicationLanguage.INSTANCE.<Object> getInstance(clazz);
	}
}
