/*
 * generated by Xtext 2.10.0
 */
package skysail.product.prototypr.dsl.idea.lang.psi;

import com.intellij.psi.util.PsiModificationTracker;
import org.eclipse.xtext.psi.BaseXtextCodeBlockModificationListener;
import skysail.product.prototypr.dsl.idea.lang.ApplicationLanguage;

public class ApplicationCodeBlockModificationListener extends BaseXtextCodeBlockModificationListener {

	public ApplicationCodeBlockModificationListener(PsiModificationTracker psiModificationTracker) {
		super(ApplicationLanguage.INSTANCE, psiModificationTracker);
	}

}
