/*
 * generated by Xtext 2.10.0
 */
package skysail.product.prototypr.dsl.idea.completion

import org.eclipse.xtext.idea.lang.AbstractXtextLanguage
import skysail.product.prototypr.dsl.idea.lang.ApplicationLanguage

class ApplicationCompletionContributor extends AbstractApplicationCompletionContributor {
	new() {
		this(ApplicationLanguage.INSTANCE)
	}
	
	new(AbstractXtextLanguage lang) {
		super(lang)
		//custom rules here
	}
}
